pipelines:
  test:
    group: dummy
    materials:
      dummy:
        plugin_configuration:
          id: github.pr
          version: 1.3.5
        options:
          url: "git@github.com:yoon-youngjin/dummy.git"
          branch: main
#          filter:
#            state: open
    stages:
      - test:
          jobs:
            test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test