pipelines:
  test:
    group: defaultGroup
    materials:
      dummy:
        git: https://github.com/yoon-youngjin/dummy
        branch: main
    stages:
      - test:
          jobs:
            test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test