apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - name: dummy
          image: yoon11/dummy:latest
          ports:
            - containerPort: 8080