pipelines:
  test:
    group: dummy
    label_template: ${COUNT}-${dummy[:10]}
    materials:
      dummy:
        git: https://github.com/yoon-youngjin/dummy
        branch: main
    stages:
      - test:
          jobs:
            test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test
  build:
    group: dummy
    label_template: ${COUNT}-${dummy[:10]}
    environment_variables:
      DOCKER_HUB_PASSWORD: "{{SECRET:[dummy-secret][DOCKER_HUB_PASSWORD]}}"
    materials:
      dummy:
        git: https://github.com/yoon-youngjin/dummy
        branch: main
    stages:
      - build:
          jobs:
            build-and-push-docker:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        docker build -t yoon11/dummy:${GO_PIPELINE_LABEL} .
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - "echo $DOCKER_HUB_PASSWORD | docker login -u yoon11 --password-stdin"
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        docker push yoon11/dummy:${GO_PIPELINE_LABEL}
  deploy:
    group: dummy
    label_template: ${UPSTREAM}
    materials:
      upstream:
        pipeline: build
        stage: build
    stages:
      - deploy:
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            deploy:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - |
                        git clone -b main https://github.com/yoon-youngjin/gocd-config.git
                        
                        helm template \
                        gocd-config/dummy \
                        -f gocd-config/dummy/values.yaml \
                        --set version=${GO_PIPELINE_LABEL} \
                        > deploy.yaml
                        
                        cat deploy.yaml
                        
                        kubectl apply -n test -f deploy.yaml
