pipelines:
  test:
    group: dummy
    materials:
      dummy:
        git: https://github.com/yoon-youngjin/dummy
        branch: main
    stages:
      - test:
          jobs:
            test:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - test
  build:
    group: dummy
    environment_variables:
      DOCKER_HUB_PASSWORD: "{{SECRET:[dummy-secret][DOCKER_HUB_PASSWORD]}}"
    materials:
      source:
        git: https://github.com/yoon-youngjin/dummy
        branch: main
    stages:
      - build:
          jobs:
            build-and-push-docker:
              tasks:
                - exec:
                    command: ./gradlew
                    arguments:
                      - build
                - exec:
                    command: docker
                    arguments:
                      - build
                      - "-t"
                      - "yoon11/dummy:latest"
                      - "."
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - "echo $DOCKER_HUB_PASSWORD | docker login -u yoon11 --password-stdin"
                - exec:
                    command: docker
                    arguments:
                      - push
                      - "yoon11/dummy:latest"
  deploy:
    group: dummy
    materials:
      upstream:
        pipeline: build
        stage: build
    stages:
      - deploy:
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            deploy:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - "-c"
                      - |
                        git clone -b main https://github.com/yoon-youngjin/gocd-config.git
                        
                        kubectl apply -n test -f gocd-config/dummy/deployment.yaml 
                        kubectl apply -n test -f gocd-config/dummy/service.yaml
